config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home#index'

  get 'about' => 'home#about'
  get 'faq' => 'home#faq'

  get 'sessions/new'

  post 'sessions' => 'sessions#create'

  post 'sessions/destroy'

  get 'properties/new'

  post 'properties/create'

  post 'bids/accept' => 'bids#accept'
  post 'userskills' => 'userskills#create'

  resources :users, only: [:create, :new, :show, :edit, :update] do
    resources :user_skills, only: [:create, :update]
  end

  resources :jobs do
    resources :bids, only: [:create, :new] do
      resources :reviews, only: [:create, :new]
    end
    resources :bids, only: [:create, :new, :accept]
  end

  root 'home#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  has_many    :bids
  has_many    :reviews, through: :bids
  has_many    :job_skills
  has_many    :skills, through: :job_skills
  belongs_to  :property
  validates :title, presence: true
  validates :max_bid, presence: true
  validates :description, presence: true

  validates :start_date, :end_date, presence: true
  validate  :end_is_after_start, :start_after_today, :bidding_ends_before_start
  validate  :two_reviews_max

  def end_is_after_start
    errors.add(:end_date, "must come after start date") if self.end_date < self.start_date
  end

  def two_reviews_max
    errors.add(:reviews, "cannot have more than two reviews") if self.reviews.count >= 2
  end

  def start_after_today
    errors.add(:start_date, "must be a future date") if self.start_date < Time.now
  end

  def bidding_ends_before_start
    errors.add(:bid_length, "must end before start date of job") if Time.now + self.bid_length.day >= self.start_date + 1.day
  end

  def recent_bids
    bids.order(created_at: :desc)
  end

  def landlord
    property.landlord
  end

  def accepted_bid?
    self.bids.where(accepted: true).count >= 1
  end

  def find_accepted_bid
    self.bids.where(accepted:true)[0]
  end

  def expired?
    Time.now > self.created_at + self.bid_length.day
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show]
  before_action :set_skills, only: [:new, :create]
  def new
    @job = Job.new
  end

  def create
    @job = Job.new(job_params)
    respond_to do |format|
      if at_least_one_skill_selected? && @job.save
        add_job_skills
        format.html { redirect_to home_path, notice: 'Job was successfully created.' }
        format.json { render json: @job }
      else
        format.html {render :new }
        format.json { render json: @job.errors.full_messages, status: :unprocessable_entity }
      end
    end
  end

  def index
    expires_in 5.minutes
    @jobs = Rails.cache.fetch(:jobs) do
      Job.all
    end
  end

  def show
  end

  private
  def job_params
    params.require(:job).permit(:property_id, :description, :start_date, :end_date, :max_bid, :bid_length, :title)
  end

  def set_job
    @job = Job.find(params[:id])
  end

  def set_skills
    @skills = Skill.all
  end

  def add_job_skills
    @skills.each do |skill|
      @job.skills << skill if selected_skill?(skill.name)
    end
  end

  def selected_skill?(skill)
    params[:user_skill][skill] == "1"
  end

  def at_least_one_skill_selected?
    count = @skills.select {|skill| selected_skill?(skill.name)}.length
    return true if count > 0
    @job.errors.add(:description, "Error: At least one skill must be selected")
    false
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_contractor.html.haml
%h1
  = @job.title

%div
  %p
    %b
      Description:
    %i
      = @job.description
  %p
    %b
      Max bid:
    =number_to_currency(@job.max_bid)
  %p
    %b
      Bidding ends:
    =(@job.created_at + @job.bid_length).strftime("%B %d, %Y")
  %p
    %b
      Job Time frame:
    =@job.start_date.strftime("%B %d, %Y")
    to
    =@job.end_date.strftime("%B %d, %Y")

%div
  %b
    Posted by:
  = link_to @job.landlord.name, @job.landlord
%table.table.table-hover.table-bordered
  %tr
    %th
      Name
    %th
      Amount
    %th
      Placed
  - @job.recent_bids.each do |bid|
    %tr
      %td
        = link_to bid.contractor.name, user_path(bid.contractor)
      %td
        = number_to_currency(bid.price)
      %td
        = bid.created_at.strftime("%B %d, %Y")

- unless @job.accepted_bid?
  = link_to "Place a new bid on this", new_job_bid_path(@job)

- if @job.accepted_bid?
  %h3 This job has been completed.
  %h4
    - if !@job.find_accepted_bid.reviews.where(review_for: 1).empty?
      How did the contractor do?
      = @job.find_accepted_bid.reviews.where(review_for: 1)[0].description
    - if !@job.find_accepted_bid.reviews.where(review_for: 0).empty?
      How was it working for the landlord?
      = @job.find_accepted_bid.reviews.where(review_for: 0)[0].description

app/views/jobs/_form.html.haml
%div.container
  %h1 Post a job
  - if @job.errors.any?
    .alert.alert-danger.fade.in
      %a.close{"data-dismiss" => "alert", :href => "#"} ×
      %ul
      - @job.errors.full_messages.each do |msg|
        %li
          = msg
  - doajax = false unless (defined? doajax)
  = form_for @job, remote: doajax do |f|
    %ul#job-form
      %li
        = f.collection_select :property_id, @user.properties.order(:name), :id, :name,   {prompt: "What property is this job for?"}, {class:"form-control input-sm "}

      = link_to "Add a property", properties_new_path#,  :target => "_blank"
      %li
        = f.label :title, "Job Title"
        = f.text_field :title, :placeholder => "Fix the sink", class: "form-control"
      %li
        = f.label :description, "Job Description"
        = f.text_area(:description, columns: 30, rows: 2, class: "form-control")
      %li
        %h4 Skills needed for this job
        = render partial: 'jobs/skills'
      %li
        = f.label :start_date, "Start Date"
        = f.date_select :start_date, placeholder: "12/10/2014", id: "start_date"
      %li
        = f.label :end_date, "End Date"
        = f.date_select :end_date, :placeholder => "12/10/2014", id: "end_date"
      %li
        = f.label :max_bid, "Max Bid"
        = f.text_field :max_bid, id: "max_bid", class: "form-control"
      %li
        = f.label :bid_length
        = f.select(:bid_length, options_for_select([['1 Day', 1], ['2 Days', 2], ['3 Days', 3], ['4 Days', 4], ['5 Days', 5], ['6 Days', 6], ['7 Days', 7], ['8 Days', 8]]))
      %li
        = f.submit "Create Job", class: "btn btn-primary"


:javascript
  $(function() {
    $('#start_date').datepicker();
    $('#end_date').datepicker();
  });

app/views/jobs/_landlordbids.html.haml
%h1= @job.title

%hr

%div
  %p
    %b
      Description:
    = @job.description
  %p
    %b
      Max bid:
    =number_to_currency(@job.max_bid)
  %p
    %b
      Bidding ends:
    =(@job.created_at + @job.bid_length).strftime("%B %d, %Y")
  %p
    %b
      Job time frame:
    =@job.start_date.strftime("%B %d, %Y")
    to
    =@job.end_date.strftime("%B %d, %Y")
%div
  %b
    Posted by:
  = link_to @job.landlord.name, @job.landlord
- unless @job.accepted_bid?
  Bids on this job
  %table.table.table-striped.table-hover
    %tr
      %th
        Name
      %th
        Amount
      %th
        Placed
      %th
        Accept
    - @job.recent_bids.each do |bid|
      %tr{bid_id: bid.id}
        %td
          = bid.contractor.name
        %td
          = number_to_currency(bid.price)
        %td
          = bid.created_at.strftime("%B %d, %Y")
        %td
          %button.accept-bid.btn.btn-default
            Accept Bid
- if @job.accepted_bid?
  %h3 This job has been completed.
  %h4
    - if !@job.find_accepted_bid.reviews.where(review_for: 1).empty?
      How did the contractor do?
      = @job.find_accepted_bid.reviews.where(review_for: 1)[0].description
    - if !@job.find_accepted_bid.reviews.where(review_for: 0).empty?
      How was it working for the landlord?
      = @job.find_accepted_bid.reviews.where(review_for: 0)[0].description

app/views/jobs/_skills.html.haml
= fields_for :user_skill do |skill_field|
  %ul
    -@skills.each do |skill|
      %li
        =skill_field.label skill.name
        =skill_field.check_box skill.name

app/views/jobs/index.html.haml
%ul
- @pending_jobs.each do |j|
  %li
    = j.description

app/views/jobs/new.html.haml
= render partial: 'form'

app/views/jobs/show.html.haml
%h1
.container
  = render partial: "landlordbids" if @user.user_type == 'landlord'
  = render partial: "contractor" if @user.user_type == 'contractor'