config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home#index'

  get 'about' => 'home#about'
  get 'faq' => 'home#faq'

  get 'sessions/new'

  post 'sessions' => 'sessions#create'

  post 'sessions/destroy'

  get 'properties/new'

  post 'properties/create'

  post 'bids/accept' => 'bids#accept'
  post 'userskills' => 'userskills#create'

  resources :users, only: [:create, :new, :show, :edit, :update] do
    resources :user_skills, only: [:create, :update]
  end

  resources :jobs do
    resources :bids, only: [:create, :new] do
      resources :reviews, only: [:create, :new]
    end
    resources :bids, only: [:create, :new, :accept]
  end

  root 'home#index'

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_user, :set_skills

  def about

  end

  def index
    if contractor?
      @my_jobs = @user.all_jobs_i_bid_on
      @my_open_jobs = @user.open_jobs_i_bid_on_cached
      @my_completed_jobs = @user.completed_cached
      elsif landlord?
        @job = Job.new
        @properties = @user.properties
    end
    if landlord?
      lord_pending_jobs
      lord_completed_jobs
      my_properties
    end
  end

  private

  def set_user
    @user ||= User.find(session[:user_id])
  end

  def landlord?
    @user.user_type == 'landlord'
  end

  def contractor?
    @user.user_type == 'contractor'
  end

  def lord_completed_jobs
    @lord_completed_jobs = []
    @user.jobs.each do |job|
      @lord_completed_jobs << job if job.accepted_bid?
    end
  end

  def lord_pending_jobs
    @lord_pending_jobs = []
    @user.jobs.each do |job|
      @lord_pending_jobs << job unless job.accepted_bid?
    end
  end

  def set_skills
    @skills = Skill.all
  end

  def my_properties
    @properties = @user.properties
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contractor.html.haml
=render partial: 'no_skills' if @user.skills.length == 0
%div#main-container.container-fluid.container
  %div#row
    %div#sidebar.col-xs-4
      %h2 My Bids
      %table.table.table-hover.table-bordered
        - @my_open_jobs.each do |job|
          %tr
            %td= link_to job.title, job
    %div#sidebar.col-xs-4
      %h2 Available Jobs
      %table.table.table-hover.table-striped
        -@user.skills.each do |skill|
          %tr
            %td.info
              =skill.name
          - (skill.available_jobs - @my_jobs).each do |job|
            %tr
            %td.col-xs-4
              %td.col-xs-8
                = link_to job.title, job
    %div#sidebar.col-xs-4
      %h2 Completed Jobs
      %table.table.table-hover.table-bordered
        - @my_completed_jobs.each do |completed_job|
          %tr
            %td= link_to completed_job.title, completed_job
            - if completed_job.reviews.where(review_for: 0).empty?
              %td=link_to 'Add a Review', new_job_bid_review_path(completed_job, completed_job.find_accepted_bid)
              - if completed_job.reviews.count == 0
                %td You need to add a review!

app/views/home/_landlord.html.haml
%div#main-container.container.container-fluid
  %div#row
    %div#sidebar.col-xs-4
      %h2 Open Jobs
      %table.table.table-hover.table-bordered
        - @lord_pending_jobs.each do |job|
          %tr
            %td= link_to job.title, job
        %tr.success.active
          %td= link_to 'Add a Job', new_job_path, id: "add_a_job_link"
    %div#sidebar.col-xs-4
      %h2 Completed Jobs
      %table.table.table-hover.table-bordered
        - @lord_completed_jobs.each do |completed_job|
          %tr
            %td=link_to completed_job.title, completed_job
            - if completed_job.reviews.where(review_for: 1).empty?
              %td=link_to 'Add a Review', new_job_bid_review_path(completed_job, completed_job.find_accepted_bid)
    %div#sidebar.col-xs-4
      %h2 My properties
      %table.table.table-hover.table-bordered
        - @properties.order(:name).each do |property|
          %tr
            %td
              = property.name
            %td
              = property.address

app/views/home/_no_skills.html.haml
%div
  %h2
  You currently do not have any skills in your profile.
  = link_to "Update My Profile", edit_user_path(@user)

app/views/home/about.html.haml
%h1 About Fix8

app/views/home/faq.html.haml
%h1 FAQs

app/views/home/index.html.haml
%h1
= render partial: "landlord" if @user.user_type == 'landlord'
= render partial: "contractor" if @user.user_type == 'contractor'