config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home#index'

  get 'about' => 'home#about'
  get 'faq' => 'home#faq'

  get 'sessions/new'

  post 'sessions' => 'sessions#create'

  post 'sessions/destroy'

  get 'properties/new'

  post 'properties/create'

  post 'bids/accept' => 'bids#accept'
  post 'userskills' => 'userskills#create'

  resources :users, only: [:create, :new, :show, :edit, :update] do
    resources :user_skills, only: [:create, :update]
  end

  resources :jobs do
    resources :bids, only: [:create, :new] do
      resources :reviews, only: [:create, :new]
    end
    resources :bids, only: [:create, :new, :accept]
  end

  root 'home#index'

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  before_action :unaccepted_bid

  def new
    @review = Review.new
    @bid = Bid.find(params[:bid_id])
  end

  def create
    @review = Review.new(review_params)
    @review.bid_id = params[:bid_id]
    assign_to_user_type
    if @review.save
      redirect_to recipient_of_review
    else
      render :new
    end
  end

  private

  def unaccepted_bid
    unless Bid.find(params[:bid_id]).accepted
      redirect_to home_path
    end
  end

  def review_params
    params.require(:review).permit(:rating, :description)
  end

  def assign_to_user_type
    if @user.user_type == 'landlord'
      @review.review_for = 'contractor'
    else
      @review.review_for = 'landlord'
    end
  end

  def recipient_of_review
    bid = Bid.find(params[:bid_id])
    if @user.user_type == 'landlord'
      bid.contractor
    else
      bid.job.landlord
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.haml
= form_for @review, url: job_bid_reviews_path do |f|
  %ul
    %li
      = f.label :rating
      = f.select(:rating, options_for_select([['0',0],['1',1],['2',2],['3',3],['4',4],['5',5],['6',6],['7',7],['8',8],['9',9],['10',10]]))
    %li
      = f.label :description, "Comments"
      %div
        = f.text_area :description, :placeholder => "What should others know? "
    %li
      = f.submit "Submit", class: "btn btn-primary"

app/views/reviews/new.html.haml
%h1
.container
  %h3
    Add a review for
    -if @user.user_type == "contractor"
      =@bid.job.landlord.name
    -if @user.user_type == "landlord"
      =@bid.contractor.name
    in regards to
    =@bid.job.title
  = render partial: "form"