config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home#index'

  get 'about' => 'home#about'
  get 'faq' => 'home#faq'

  get 'sessions/new'

  post 'sessions' => 'sessions#create'

  post 'sessions/destroy'

  get 'properties/new'

  post 'properties/create'

  post 'bids/accept' => 'bids#accept'
  post 'userskills' => 'userskills#create'

  resources :users, only: [:create, :new, :show, :edit, :update] do
    resources :user_skills, only: [:create, :update]
  end

  resources :jobs do
    resources :bids, only: [:create, :new] do
      resources :reviews, only: [:create, :new]
    end
    resources :bids, only: [:create, :new, :accept]
  end

  root 'home#index'

end

app/views/layouts/_header.html.haml
%nav.navbar.navbar-default{role: "navigation"}

  .navbar-header
    %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", type: "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    .accessible
      <a href="#content">Skip to main content</a>
      <a href="#main_nav">Skip to navigation</a>
    = link_to image_tag('fix8_logo.png', id: 'logo'), root_path, :class => 'navbar-brand', :id => 'logo'
    /‘infinite possibilities for getting your jobs done’
  / Collect the nav links, forms, and other content for toggling
  .navbar-collapse.collapse
    %ul.nav.navbar-nav.navbar-right
      %li
        =link_to "Home", root_path

      - if current_user
        %li
          = link_to "Edit Profile", edit_user_path(@user)

        %li
          /= link_to "Sign Out", sessions_destroy_path, method: :delete
          = link_to "Sign Out", sessions_destroy_path, :method => :destroy

      - else
        %li
          = link_to "Sign In", root_path

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Fix8
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .col-md-12.col-lg-12.col-sm-12#universal-container
      .content#content
        %header
          = render partial: 'layouts/header'
        = yield